services:

  python-api:
    image: python-api
    build:
      context: api/   # Ubicacion del dockerfile
    container_name: python-api  # Nombre del contenedor
    hostname: python-api  # Nombre de host dentro de la red de Docker
    networks:
      - inventario-net  # Conecta los contenedores a la misma red
    environment:
      - DBCONN #Conexion a la bd de mongo
      - TZ  # Zona horaria
    ports:
      - "8080:8080"  # Expone el puerto 8000 externamente
    restart: always  # Reinicia siempre si falla
    profiles:
      - full  # Perfil de ejecución específico
      - back

networks:
  inventario-net:
    name: inventario-net  # Define una red
    driver: bridge